on: [push]

jobs:
  build_rom:
    runs-on: ubuntu-latest
    container: igwgames/create-nes-game:v1.0.12

    name: Compile rom
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Move things into the spots github CI expects them in
        run: "cp -a /root/. /github/home"
      - name: Install dependencies
        run: create-nes-game download-dependencies --assume-yes
      - name: Build the game
        run: create-nes-game build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Game Download
          path: rom
